"""make user and employee cascade delete

Revision ID: 2916e1f2d3f6
Revises: 6147d753042d
Create Date: 2025-01-13 17:06:55.706566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2916e1f2d3f6'
down_revision = '6147d753042d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_employee_id_employee', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_user_employee_id_employee'), 'employee', ['employee_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_employee_id_employee'), type_='foreignkey')
        batch_op.create_foreign_key('fk_user_employee_id_employee', 'employee', ['employee_id'], ['id'])

    # ### end Alembic commands ###
