"""add employee id

Revision ID: 2c3357c791f0
Revises: 4bd253583d67
Create Date: 2024-12-28 21:36:24.648512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c3357c791f0'
down_revision = '4bd253583d67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_id', sa.String(length=36), nullable=True))
        batch_op.create_unique_constraint('uq_employee_id', ['employee_id'])
        batch_op.create_foreign_key(batch_op.f('fk_user_employee_id_employee'), 'employee', ['employee_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_employee_id_employee'), type_='foreignkey')
        batch_op.drop_constraint('uq_employee_id', type_='unique')
        batch_op.drop_column('employee_id')

    # ### end Alembic commands ###
