"""remove employee id

Revision ID: 4bd253583d67
Revises: 509590f16e6e
Create Date: 2024-12-28 21:35:34.992696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bd253583d67'
down_revision = '509590f16e6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_employee_id', type_='unique')
        batch_op.drop_constraint('fk_user_employee_id_employee', type_='foreignkey')
        batch_op.drop_column('employee_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_id', sa.VARCHAR(length=36), nullable=True))
        batch_op.create_foreign_key('fk_user_employee_id_employee', 'employee', ['employee_id'], ['id'])
        batch_op.create_unique_constraint('uq_employee_id', ['employee_id'])

    # ### end Alembic commands ###
