"""empty message

Revision ID: 6147d753042d
Revises: f4857b51b23d
Create Date: 2025-01-02 17:32:13.080658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6147d753042d'
down_revision = 'f4857b51b23d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_constraint('uq_employee_id', type_='unique')

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_constraint('uq_department_id', type_='unique')
        batch_op.drop_constraint('uq_user_email', type_='unique')

    with op.batch_alter_table('leave', schema=None) as batch_op:
        batch_op.drop_constraint('uq_employee_id', type_='unique')

    with op.batch_alter_table('payroll', schema=None) as batch_op:
        batch_op.drop_constraint('uq_employee_id', type_='unique')

    with op.batch_alter_table('performance', schema=None) as batch_op:
        batch_op.drop_constraint('uq_employee_id', type_='unique')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_employee_id', type_='unique')
        batch_op.drop_constraint('uq_user_email', type_='unique')
        batch_op.drop_constraint('uq_user_username', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_username', ['username'])
        batch_op.create_unique_constraint('uq_user_email', ['email'])
        batch_op.create_unique_constraint('uq_employee_id', ['employee_id'])

    with op.batch_alter_table('performance', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_employee_id', ['employee_id'])

    with op.batch_alter_table('payroll', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_employee_id', ['employee_id'])

    with op.batch_alter_table('leave', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_employee_id', ['employee_id'])

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_email', ['email'])
        batch_op.create_unique_constraint('uq_department_id', ['department_id'])

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_employee_id', ['employee_id'])

    # ### end Alembic commands ###
