"""empty message

Revision ID: 6ec58bf5ceb1
Revises: 2916e1f2d3f6
Create Date: 2025-01-13 17:13:08.707755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ec58bf5ceb1'
down_revision = '2916e1f2d3f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_employee_id_employee', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_user_employee_id_employee'), 'employee', ['employee_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user_employee_id_employee'), type_='foreignkey')
        batch_op.create_foreign_key('fk_user_employee_id_employee', 'employee', ['employee_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
