"""empty message

Revision ID: 9027637c6e8a
Revises: 6ec58bf5ceb1
Create Date: 2025-01-13 17:30:48.947461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9027637c6e8a'
down_revision = '6ec58bf5ceb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_constraint('fk_employee_department_id_department', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_employee_department_id_department'), 'department', ['department_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_employee_department_id_department'), type_='foreignkey')
        batch_op.create_foreign_key('fk_employee_department_id_department', 'department', ['department_id'], ['id'])

    # ### end Alembic commands ###
